services:
  - type: web
    name: videogen
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    disk:
      name: video-storage
      mountPath: /tmp/video-cache
      sizeGB: 1
    envVars:
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: MAX_CONCURRENT_TASKS
        value: "1"
      - key: RENDER_MEMORY_LIMIT
        value: "512"
      - key: EXTREME_MEMORY_SAVING
        value: "true"
      - key: DISABLE_VIDEO_PROCESSING
        value: "true"
      - key: PEXELS_API_KEY
        value: "wDEUJxQv8o9VV0gYat55LnXh0Sl9YlKBH5qZCOlDp03oEKGxJSXX23IH"
      - key: LLM_PROVIDER
        value: "pollinations"
      - key: POLLINATIONS_MODEL
        value: "openai-fast"
      - key: CLEANUP_DAYS
        value: "2"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: moneyprinterturbo-storage
      mountPath: /MoneyPrinterTurbo/storage
      sizeGB: 10
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 70
      targetCPUPercent: 60
